name = "FindRoot"
uuid = "7b3277fd-f8eb-49fb-bfb0-9edc1afb3aec"
authors = ["Kiar Fatah"]
version = "0.1.0"

[compat]
julia = "1.7.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
